### ISSUE TITLE
Suppress INFO and DEBUG messages

### ISSUE THREAD

**Issue by h4iku** [Salehbigdeli/bekeshbiron#1]
Hello dear developer,
Is suppressing other kinds of messages like INFO and DEBUG in the scope of this module? It would be nice to have this option, for example, to suppress TensorFlow logs.

Thanks :)

**Comment by Salehbigdeli** [comment]
Hi,
Adding these functionalities need API change and we manage to add them in future major version release (since lots of current users are depend on current API).
I  got notification for this issue but for "Ba Class Bazi" reasons, I have postponed answering you!

Regards :))
